server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 111.229.224.94
aliyun:
  sms:
    accessKeyId: LTAINCGR6RLXTBIv
    accessKeySecret: Ek9Fj6d22ouIwc0u5gVdehwgeEtgFo
    template_code: SMS_170350699
    sign_name: 十次方